routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');

Route::group(['namespace' => 'Backend', 'middleware' => ['auth']], function () {

    Route::get('/messages', 'ChatController@fetchAllMessages');
    Route::post('/messages', 'ChatController@sendMessage');

    Route::post('team/add/team/member', 'TeamController@addTeamMember')->name('team.add.team.member');
    Route::resource('team', 'TeamController');
    Route::get('team/status/{id}', 'TeamController@status')->name('team.status');

    Route::post('team/create', 'TeamController@createTeam')->name('team.create');

    Route::group(['middleware' => [/*'admin', 'organizer'*/]], function () {

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('player', 'UserController@player')->name('player');

        Route::resource('user', 'UserController');
        Route::get('user/status/{id}', 'UserController@status')->name('user.status');

        Route::resource('shop', 'ShopController');
        Route::get('shop/status/{id}', 'ShopController@status')->name('shop.status');

        Route::resource('tournament', 'TournamentController');
        Route::get('tournament/status/{id}', 'TournamentController@status')->name('tournament.status');
        Route::get('tournament/{id}/start', 'TournamentController@start')->name('tournament.start');
        Route::post('tournament/{id}/start', 'TournamentController@storeMatch')->name('tournament.start.store');

        Route::resource('match', 'MatchController');
    });

    Route::group(['prefix' => 'player', 'as' => 'player.', 'middleware' => ['player']], function () {

//        Route::get('chats', 'ChatController@index')->name('chats');

        Route::get('dashboard', 'PlayerController@dashboard')->name('dashboard');
        Route::get('chat', 'PlayerController@chat')->name('chat');
        Route::get('profile/{id}', 'PlayerController@profile')->name('profile');
        Route::put('profile/{id}', 'PlayerController@updateProfile')->name('profile.update');
        Route::get('team', 'PlayerController@team')->name('team');

        Route::get('join/team/{id}', 'PlayerController@joinTeam')->name('join.team');
        Route::post('join/team', 'PlayerController@storeTeam')->name('join.team.store');

        Route::get('join/tournament/{id}', 'PlayerController@joinTournament')->name('join.tournament');
        Route::post('join/tournament', 'PlayerController@storeTournament')->name('join.tournament.store');

        Route::get('tournament', 'PlayerController@tournament')->name('tournament');
        Route::get('shop', 'PlayerController@shop')->name('shop');

        Route::post('buy', 'PlayerController@shopItem')->name('buy');
    });

});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{
    use HasFactory;

    protected $table = 'shops';

    protected $fillable = [
        'image',
        'title',
        'price',
        'star',
        'description',
        'status'
    ];
}

app/Http/Controllers/Backend/PlayerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Shop;
use App\Models\Chat;
use App\Models\Team;
use App\Models\TeamMember;
use App\Models\TeamTournament;
use App\Models\Tournament;
use App\Models\User;
use App\Models\UserShop;
use App\Models\UserTournament;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PlayerController extends Controller
{
    protected $viewPath = 'backend.player';

    protected $folder = 'user';
    protected $folder_path;

    public function __construct()
    {
        $this->folder_path = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . $this->folder . DIRECTORY_SEPARATOR;
    }

    public function dashboard()
    {
        $data = [];
        $data['coins'] = Shop::where('status', 1)->get();
        $data['userShop'] = UserShop::where('user_id', auth()->user()->id)->get();
        $data['teamUser'] = TeamMember::where('user_id', auth()->user()->id)->first();
        $data['userTournament'] = UserTournament::where('user_id', auth()->user()->id)->get();
        return view($this->viewPath . '.dashboard.index', compact('data'));
    }

    public function chat()
    {
        $data = [];
        $data['messages'] = Chat::select('id', 'user_id', 'message')->get();
        return view($this->viewPath . '.chat.index', compact('data'));
    }

    public function profile($id)
    {
        $data = [];
        $data['row'] = User::where('id', $id)->first();
        return view($this->viewPath . '.profile.index', compact('data'));
    }

    public function updateProfile(Request $request, $id)
    {
        $user = User::where('id', $id)->first();
        if ($request->has('main_image')) {
            $file = $request->file('main_image');
            $fileName = Str::random(25) . '.' . $file->getClientOriginalExtension();
            $file->move($this->folder_path, $fileName);
            $request->merge(['image' => $fileName]);

            if ($user->image) {
                if (file_exists($this->folder_path . $user->image)) {
                    unlink($this->folder_path . $user->image);
                }
            }
        }
        $user->update($request->all());
        return redirect()->route('player.dashboard');
    }

    public function shop()
    {
        $data = [];
        $data['shops'] = Shop::where('status', 1)->get();
        return view($this->viewPath . '.shop.index', compact('data'));
    }

    public function team(Request $request)
    {
        $data = [];
        $data['team'] = Team::with('users')
            ->where('name', 'LIKE', '%' . $request->get('team') . '%')
            ->paginate(5);
        return view($this->viewPath . '.team.index', compact('data'));
    }

    public function joinTeam($id)
    {
        $data = [];
        $data['row'] = Team::where('id', $id)->first();
        return view($this->viewPath . '.team.join', compact('data'));
    }

    public function storeTeam(Request $request)
    {
        $teamMember = TeamMember::select('user_id')->where('user_id', auth()->user()->id)->first();
        if ($teamMember === null) {
            TeamMember::create([
                'team_id' => $request->get('team_id'),
                'user_id' => auth()->user()->id,
            ]);
            alert()->success('you have joined the team successfully !!')->toToast();
        } else {
            alert()->info('you have already joined other team !!')->toToast();
        }
        return redirect()->route('player.team');
    }

    public function tournament(Request $request)
    {
        $data = [];
        $data['tournaments'] = Tournament::where('name', 'LIKE', '%' . $request->get('tournament') . '%')
            ->paginate(5);
        return view($this->viewPath . '.tournament.index', compact('data'));
    }

    public function joinTournament($id)
    {
        $data = [];
        $data['row'] = Tournament::where('id', $id)->first();
        $data['myTeam'] = TeamMember::where('user_id', auth()->user()->id)->first();
        return view($this->viewPath . '.tournament.join', compact('data'));
    }

    public function storeTournament(Request $request)
    {
        $tournamentMemberTeam = TeamTournament::select('team_id')->where('team_id', $request->get('team_id'))->first();
        if ($tournamentMemberTeam === null) {
            TeamTournament::create([
                'team_id' => $request->get('team_id'),
                'tournament_id' => $request->get('tournament_id'),
            ]);
        }
        alert()->success('you have joined the tournament successfully !!')->toToast();
        return redirect()->route('player.tournament');
    }

    public function shopItem(Request $request)
    {
        if (auth()->user()->number_of_coins > $request->get('costCoin')) {
            auth()->user()->update([
                'number_of_coins' => auth()->user()->number_of_coins - $request->get('costCoin')
            ]);
            UserShop::create([
                'user_id' => auth()->user()->id,
                'shop_id' => $request->get('shop_id'),
                'coin' => $request->get('costCoin'),
            ]);
            alert()->success('you have successfully purchased !!')->toToast();
            return redirect()->back();
        }
        alert()->warning('you do not have enough coins !!')->toToast();
        return redirect()->back();
    }
}

app/Http/Controllers/Backend/ShopController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\ShopsDataTable;
use App\Http\Helper\MessageService;
use App\Http\Requests\Shop\StoreRequest;
use App\Http\Requests\Shop\UpdateRequest;
use App\Models\Shop;
use Illuminate\Support\Str;

class ShopController extends BaseController
{
    protected $baseRoute = 'shop';
    protected $viewPath = 'backend.shop';
    protected $panel = 'Shop';
    protected $folder = 'shop';
    protected $folder_path;

    private $messageService;

    public function __construct(MessageService $messageService)
    {
        $this->messageService = $messageService;
        $this->folder_path = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . $this->folder . DIRECTORY_SEPARATOR;
    }

    public function index(ShopsDataTable $shopsDataTable)
    {
        return $shopsDataTable->render(parent::loadDataToView($this->viewPath . '.index'));
    }

    public function create()
    {
        $data = [];
        $data['model'] = new Shop();
        return view(parent::loadDataToView($this->viewPath . '.create'), compact('data'));
    }

    public function store(StoreRequest $request)
    {
        if ($request->has('main_image')) {
            $file = $request->file('main_image');
            $fileName = Str::random(25) . '.' . $file->getClientOriginalExtension();
            $file->move($this->folder_path, $fileName);
            $request->merge(['image' => $fileName]);
        }
        Shop::create($request->all());
        $this->messageService->successMessageToDisplay('success', $this->panel, 'added');
        return redirect()->route($this->baseRoute . '.index');
    }

    public function edit($id)
    {
        $data = [];
        $data['row'] = Shop::where('id', $id)->first();
        return view(parent::loadDataToView($this->viewPath . '.edit'), compact('data'));
    }

    public function update(UpdateRequest $request, $id)
    {
        $shop = Shop::where('id', $id)->first();
        if ($request->has('main_image')) {
            $file = $request->file('main_image');
            $fileName = Str::random(25) . '.' . $file->getClientOriginalExtension();
            $file->move($this->folder_path, $fileName);
            $request->merge(['image' => $fileName]);

            if ($shop->image) {
                if (file_exists($this->folder_path . $shop->image)) {
                    unlink($this->folder_path . $shop->image);
                }
            }
        }
        $shop->update($request->all());
        $this->messageService->successMessageToDisplay('success', $this->panel, 'updated');
        return redirect()->route($this->baseRoute . '.index');
    }

    public function destroy($id)
    {
        $shop = Shop::where('id', $id)->first();
        $shop->delete();
        $this->messageService->successMessageToDisplay('success', $this->panel, 'deleted');
        return redirect()->route($this->baseRoute . '.index');
    }

    public function status($id)
    {
        $shop = Shop::where('id', $id)->first();
        $shop->status = !$shop->status;
        $shop->save();
        $this->messageService->successMessageToDisplay('success', $this->panel, 'updated');
        return redirect()->route($this->baseRoute . '.index');
    }
}

resources/views/backend/player/shop/index.blade.php
@extends('backend.player.master')
@section('content')
    <section class="breadcrumbs" id="middle1">
        <div class="container" id="middle2">

            <div class="d-flex justify-content-between align-items-center">
                <h1>Meepos Shop</h1>
                <ol>
                    <li><a href="{{ route('player.dashboard') }}">Home</a></li>
                    <li>Meepos Shop</li>
                </ol>
            </div>

        </div>
    </section>

    <div class="container2">
        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{{ asset('player/asset/img/steam.png') }}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{{ asset('player/asset/img/steam2.png') }}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{{ asset('player/asset/img/steam3.png') }}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>

                <br>
                <br>
            </div>

            <div class="row">

                @if(isset($data['shops']))
                    @foreach($data['shops'] as $coin)
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                @if(isset($coin->image))
                                    <a href="#"><img class="card-img-top"
                                                     src="{{ asset('uploads/shop/'.$coin->image) }}" alt=""></a>
                                @else
                                    <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                                @endif

                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ $coin->title }}</a>
                                    </h4>
                                    <h5>Ec. {{ $coin->price }}</h5>
                                    <p class="card-text">{!! \Illuminate\Support\Str::words($coin->description,10) !!}</p>
                                </div>
                                <form action="{{ route('player.buy') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" name="costCoin" value="{{ $coin->price }}">
                                    <input type="hidden" name="shop_id" value="{{ $coin->id }}">
                                    <button class="btn-block" type="submit">buy</button>
                                </form>
                                <div class="card-footer">
                                    <small class="text-muted">&#9733; &#9733; &#9733; &#9734; &#9734;</small>
                                </div>
                            </div>
                        </div>
                    @endforeach
                @endif

            </div>
        </div>
    </div>
@endsection