routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::view('/', 'welcome');

Route::group(['namespace' => 'Backend', 'middleware' => ['auth']], function () {

    Route::get('/messages', 'ChatController@fetchAllMessages');
    Route::post('/messages', 'ChatController@sendMessage');

    Route::post('team/add/team/member', 'TeamController@addTeamMember')->name('team.add.team.member');
    Route::resource('team', 'TeamController');
    Route::get('team/status/{id}', 'TeamController@status')->name('team.status');

    Route::post('team/create', 'TeamController@createTeam')->name('team.create');

    Route::group(['middleware' => [/*'admin', 'organizer'*/]], function () {

        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('player', 'UserController@player')->name('player');

        Route::resource('user', 'UserController');
        Route::get('user/status/{id}', 'UserController@status')->name('user.status');

        Route::resource('shop', 'ShopController');
        Route::get('shop/status/{id}', 'ShopController@status')->name('shop.status');

        Route::resource('tournament', 'TournamentController');
        Route::get('tournament/status/{id}', 'TournamentController@status')->name('tournament.status');
        Route::get('tournament/{id}/start', 'TournamentController@start')->name('tournament.start');
        Route::post('tournament/{id}/start', 'TournamentController@storeMatch')->name('tournament.start.store');

        Route::resource('match', 'MatchController');
    });

    Route::group(['prefix' => 'player', 'as' => 'player.', 'middleware' => ['player']], function () {

//        Route::get('chats', 'ChatController@index')->name('chats');

        Route::get('dashboard', 'PlayerController@dashboard')->name('dashboard');
        Route::get('chat', 'PlayerController@chat')->name('chat');
        Route::get('profile/{id}', 'PlayerController@profile')->name('profile');
        Route::put('profile/{id}', 'PlayerController@updateProfile')->name('profile.update');
        Route::get('team', 'PlayerController@team')->name('team');

        Route::get('join/team/{id}', 'PlayerController@joinTeam')->name('join.team');
        Route::post('join/team', 'PlayerController@storeTeam')->name('join.team.store');

        Route::get('join/tournament/{id}', 'PlayerController@joinTournament')->name('join.tournament');
        Route::post('join/tournament', 'PlayerController@storeTournament')->name('join.tournament.store');

        Route::get('tournament', 'PlayerController@tournament')->name('tournament');
        Route::get('shop', 'PlayerController@shop')->name('shop');

        Route::post('buy', 'PlayerController@shopItem')->name('buy');
    });

});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Backend/BaseController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;

class BaseController extends Controller
{
    protected function loadDataToView($viewPath)
    {
        View::composer($viewPath, function ($view) {
            $view->with('baseRoute', $this->baseRoute);
            $view->with('viewPath', $this->viewPath);
            $view->with('panel', $this->panel);
        });
        return $viewPath;
    }
}

app/Http/Controllers/Backend/ChatController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Events\ChatEvent;
use App\Http\Controllers\Controller;
use App\Models\Chat;
use Illuminate\Http\Request;

class ChatController extends Controller
{
    public function index()
    {
        return view('backend.player.chat.chat');
    }

    public function fetchAllMessages()
    {
        return Chat::with('user')->get();
    }

    public function sendMessage(Request $request)
    {
        $chat = auth()->user()->messages()->create([
            'message' => $request->get('message')
        ]);
        broadcast(new ChatEvent($chat->load('user')))->toOthers();

        return ['status' => 'success'];
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Shop;
use App\Models\Team;
use App\Models\Tournament;
use App\Models\User;

class DashboardController extends BaseController
{
    public function index()
    {
        $data = [];
        $data['tournaments'] = Tournament::count();
        $data['teams'] = Team::count();
        $data['players'] = User::where('type', 3)->count();
        $data['shopItems'] = Shop::count();
        return view('backend.dashboard.index', compact('data'));
    }
}

app/Http/Controllers/Backend/MatchController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\MatchesDataTable;
use App\Http\Helper\MessageService;
use App\Models\OnGoingGame;
use App\Models\Team;
use App\Models\UserTournament;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MatchController extends BaseController
{
    protected $baseRoute = 'match';
    protected $viewPath = 'backend.match';
    protected $panel = 'Match';
    protected $folder = 'match';
    private $messageService;

    public function __construct(MessageService $messageService)
    {
        $this->messageService = $messageService;
    }

    public function index(MatchesDataTable $matchesDataTable)
    {
        return $matchesDataTable->render(parent::loadDataToView($this->viewPath . '.index'));
    }

    public function create()
    {
        $data = [];
        $data['model'] = new OnGoingGame();
        return view(parent::loadDataToView($this->viewPath . '.create'), compact('data'));
    }

    public function store(Request $request)
    {
        OnGoingGame::create($request->all());
        $this->messageService->successMessageToDisplay('success', $this->panel, 'started');
        return redirect()->route($this->baseRoute . '.index');
    }

    public function show($id)
    {
        $data = [];
        $data['row'] = OnGoingGame::where('id', $id)->first();
        return view(parent::loadDataToView($this->viewPath . '.show'), compact('data'));
    }

    public function edit($id)
    {
        $data = [];
        $data['row'] = OnGoingGame::where('id', $id)->first();
        return view(parent::loadDataToView($this->viewPath . '.edit'), compact('data'));
    }

    public function update(Request $request, $id)
    {
        try {
            $match = OnGoingGame::where('id', $id)->first();
            $match->update($request->all());
            $team = Team::where('id', $request->get('winner'))->first();
            foreach ($team->users as $user) {
                $user->update([
                    'number_of_coins' => $user->number_of_coins + $request->get('coin') / $team->users()->count()
                ]);
            }
            foreach ($team->users as $user) {
                UserTournament::create([
                    'user_id' => $user->id,
                    'tournament_id' => $request->get('winner'),
                    'coin' => $request->get('coin') / $team->users()->count(),
                ]);
            }
            $this->messageService->successMessageToDisplay('success', $this->panel, 'updated');
            return redirect()->route($this->baseRoute . '.index');
        } catch (\Exception $exception) {
            $this->messageService->successMessageToDisplay('success', '', $exception->getMessage());
            return redirect()->route($this->baseRoute . '.index');
        }
    }
}

app/Http/Controllers/Backend/PlayerController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Shop;
use App\Models\Chat;
use App\Models\Team;
use App\Models\TeamMember;
use App\Models\TeamTournament;
use App\Models\Tournament;
use App\Models\User;
use App\Models\UserShop;
use App\Models\UserTournament;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PlayerController extends Controller
{
    protected $viewPath = 'backend.player';

    protected $folder = 'user';
    protected $folder_path;

    public function __construct()
    {
        $this->folder_path = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . $this->folder . DIRECTORY_SEPARATOR;
    }

    public function dashboard()
    {
        $data = [];
        $data['coins'] = Shop::where('status', 1)->get();
        $data['userShop'] = UserShop::where('user_id', auth()->user()->id)->get();
        $data['teamUser'] = TeamMember::where('user_id', auth()->user()->id)->first();
        $data['userTournament'] = UserTournament::where('user_id', auth()->user()->id)->get();
        return view($this->viewPath . '.dashboard.index', compact('data'));
    }

    public function chat()
    {
        $data = [];
        $data['messages'] = Chat::select('id', 'user_id', 'message')->get();
        return view($this->viewPath . '.chat.index', compact('data'));
    }

    public function profile($id)
    {
        $data = [];
        $data['row'] = User::where('id', $id)->first();
        return view($this->viewPath . '.profile.index', compact('data'));
    }

    public function updateProfile(Request $request, $id)
    {
        $user = User::where('id', $id)->first();
        if ($request->has('main_image')) {
            $file = $request->file('main_image');
            $fileName = Str::random(25) . '.' . $file->getClientOriginalExtension();
            $file->move($this->folder_path, $fileName);
            $request->merge(['image' => $fileName]);

            if ($user->image) {
                if (file_exists($this->folder_path . $user->image)) {
                    unlink($this->folder_path . $user->image);
                }
            }
        }
        $user->update($request->all());
        return redirect()->route('player.dashboard');
    }

    public function shop()
    {
        $data = [];
        $data['shops'] = Shop::where('status', 1)->get();
        return view($this->viewPath . '.shop.index', compact('data'));
    }

    public function team(Request $request)
    {
        $data = [];
        $data['team'] = Team::with('users')
            ->where('name', 'LIKE', '%' . $request->get('team') . '%')
            ->paginate(5);
        return view($this->viewPath . '.team.index', compact('data'));
    }

    public function joinTeam($id)
    {
        $data = [];
        $data['row'] = Team::where('id', $id)->first();
        return view($this->viewPath . '.team.join', compact('data'));
    }

    public function storeTeam(Request $request)
    {
        $teamMember = TeamMember::select('user_id')->where('user_id', auth()->user()->id)->first();
        if ($teamMember === null) {
            TeamMember::create([
                'team_id' => $request->get('team_id'),
                'user_id' => auth()->user()->id,
            ]);
            alert()->success('you have joined the team successfully !!')->toToast();
        } else {
            alert()->info('you have already joined other team !!')->toToast();
        }
        return redirect()->route('player.team');
    }

    public function tournament(Request $request)
    {
        $data = [];
        $data['tournaments'] = Tournament::where('name', 'LIKE', '%' . $request->get('tournament') . '%')
            ->paginate(5);
        return view($this->viewPath . '.tournament.index', compact('data'));
    }

    public function joinTournament($id)
    {
        $data = [];
        $data['row'] = Tournament::where('id', $id)->first();
        $data['myTeam'] = TeamMember::where('user_id', auth()->user()->id)->first();
        return view($this->viewPath . '.tournament.join', compact('data'));
    }

    public function storeTournament(Request $request)
    {
        $tournamentMemberTeam = TeamTournament::select('team_id')->where('team_id', $request->get('team_id'))->first();
        if ($tournamentMemberTeam === null) {
            TeamTournament::create([
                'team_id' => $request->get('team_id'),
                'tournament_id' => $request->get('tournament_id'),
            ]);
        }
        alert()->success('you have joined the tournament successfully !!')->toToast();
        return redirect()->route('player.tournament');
    }

    public function shopItem(Request $request)
    {
        if (auth()->user()->number_of_coins > $request->get('costCoin')) {
            auth()->user()->update([
                'number_of_coins' => auth()->user()->number_of_coins - $request->get('costCoin')
            ]);
            UserShop::create([
                'user_id' => auth()->user()->id,
                'shop_id' => $request->get('shop_id'),
                'coin' => $request->get('costCoin'),
            ]);
            alert()->success('you have successfully purchased !!')->toToast();
            return redirect()->back();
        }
        alert()->warning('you do not have enough coins !!')->toToast();
        return redirect()->back();
    }
}

app/Http/Controllers/Backend/ShopController.php
<?php

namespace App\Http\Controllers\Backend;

use App\DataTables\ShopsDataTable;
use App\Http\Helper\MessageService;
use App\Http\Requests\Shop\StoreRequest;
use App\Http\Requests\Shop\UpdateRequest;
use App\Models\Shop;
use Illuminate\Support\Str;

class ShopController extends BaseController
{
    protected $baseRoute = 'shop';
    protected $viewPath = 'backend.shop';
    protected $panel = 'Shop';
    protected $folder = 'shop';
    protected $folder_path;

    private $messageService;

    public function __construct(MessageService $messageService)
    {
        $this->messageService = $messageService;
        $this->folder_path = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . $this->folder . DIRECTORY_SEPARATOR;
    }

    public function index(ShopsDataTable $shopsDataTable)
    {
        return $shopsDataTable->render(parent::loadDataToView($this->viewPath . '.index'));
    }

    public function create()
    {
        $data = [];
        $data['model'] = new Shop();
        return view(parent::loadDataToView($this->viewPath . '.create'), compact('data'));
    }

    public function store(StoreRequest $request)
    {
        if ($request->has('main_image')) {
            $file = $request->file('main_image');
            $fileName = Str::random(25) . '.' . $file->getClientOriginalExtension();
            $file->move($this->folder_path, $fileName);
            $request->merge(['image' => $fileName]);
        }
        Shop::create($request->all());
        $this->messageService->successMessageToDisplay('success', $this->panel, 'added');
        return redirect()->route($this->baseRoute . '.index');
    }

    public function edit($id)
    {
        $data = [];
        $data['row'] = Shop::where('id', $id)->first();
        return view(parent::loadDataToView($this->viewPath . '.edit'), compact('data'));
    }

    public function update(UpdateRequest $request, $id)
    {
        $shop = Shop::where('id', $id)->first();
        if ($request->has('main_image')) {
            $file = $request->file('main_image');
            $fileName = Str::random(25) . '.' . $file->getClientOriginalExtension();
            $file->move($this->folder_path, $fileName);
            $request->merge(['image' => $fileName]);

            if ($shop->image) {
                if (file_exists($this->folder_path . $shop->image)) {
                    unlink($this->folder_path . $shop->image);
                }
            }
        }
        $shop->update($request->all());
        $this->messageService->successMessageToDisplay('success', $this->panel, 'updated');
        return redirect()->route($this->baseRoute . '.index');
    }

    public function destroy($id)
    {
        $shop = Shop::where('id', $id)->first();
        $shop->delete();
        $this->messageService->successMessageToDisplay('success', $this->panel, 'deleted');
        return redirect()->route($this->baseRoute . '.index');
    }

    public function status($id)
    {
        $shop = Shop::where('id', $id)->first();
        $shop->status = !$shop->status;
        $shop->save();
        $this->messageService->successMessageToDisplay('success', $this->panel, 'updated');
        return redirect()->route($this->baseRoute . '.index');
    }
}

resources/views/backend/common/buttons.blade.php
<a href="{{ route($panel.'.edit',$id) }}" class="btn btn-xs btn-secondary">
    <i class="fa fa-pen"></i>
</a>
<form action="{{ route($panel.'.destroy',$id) }}" method="POST">
    @csrf
    @method('DELETE')
    <button type="submit" class="btn btn-xs btn-danger">
        <i class="fa fa-trash"></i>
    </button>
</form>

resources/views/backend/common/footer.blade.php
<footer class="main-footer">
    <!-- Default to the left -->
    <strong>Copyright &copy; {{ now()->format('Y') }} <a href="/">{{ config('app.name') }}</a>.</strong> All rights
    reserved.
</footer>

resources/views/backend/common/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>{{ config('app.name') }}</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{ asset('assets/backend/plugins/fontawesome-free/css/all.min.css') }}">
    <!-- DataTables -->
    <link rel="stylesheet"
          href="{{ asset('assets/backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet"
          href="{{ asset('assets/backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets/backend/dist/css/adminlte.min.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,400i,700" rel="stylesheet">
    @yield('css')
    <style>
        body {
            font-family: 'Poppins';
        }

        .error-message {
            width: 100%;
            margin-top: .25rem;
            font-size: 80%;
            color: #dc3545;
        }
    </style>
</head>

resources/views/backend/common/master.blade.php
<!DOCTYPE html>
<html lang="en">
@include('backend.common.head')
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
@include('backend.common.navbar')
<!-- /.navbar -->

    <!-- Main Sidebar Container -->
@include('backend.common.sidebar')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        @yield('content')
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    @include('backend.common.footer')
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('assets/backend/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('assets/backend/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('assets/backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('assets/backend/dist/js/adminlte.min.js') }}"></script>
<!-- page script -->
@include('sweetalert::alert')
@yield('js')
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true,
            "autoWidth": false,
        });
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
</script>
</body>
</html>

resources/views/backend/common/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item mr-3">
            <a href="#" class="dropdown-item">
                welcome <strong>{{ auth()->user()->name }}</strong>
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="dropdown-item" onclick="event.preventDefault();$('#logout-form').submit();">
                <i class="fa fa-sign-out-alt"></i> Logout
            </a>
        </li>
        <form id="logout-form" action="{{ route('logout') }}" method="POST">
            @csrf
        </form>
    </ul>
</nav>

resources/views/backend/common/sidebar.blade.php
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <img src="{{ asset('assets/backend/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">{{ config('app.name') }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{{ route('dashboard') }}"
                       class="{!! request()->is('dashboard')?'nav-link active':'nav-link' !!}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('user.index') }}"
                       class="{!! request()->is('user*')?'nav-link active':'nav-link' !!}">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            User
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('shop.index') }}"
                       class="{!! request()->is('shop*')?'nav-link active':'nav-link' !!}">
                        <i class="nav-icon fas fa-coins"></i>
                        <p>
                            Shop
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('team.index') }}"
                       class="{!! request()->is('team*')?'nav-link active':'nav-link' !!}">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Team
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('tournament.index') }}"
                       class="{!! request()->is('tournament*')?'nav-link active':'nav-link' !!}">
                        <i class="nav-icon fas fa-gamepad"></i>
                        <p>
                            Tournament
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('match.index') }}"
                       class="{!! request()->is('match*')?'nav-link active':'nav-link' !!}">
                        <i class="nav-icon fas fa-magic"></i>
                        <p>
                            Match
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/backend/common/status.blade.php
<a href="{{ route($panel.'.status',$id) }}">
    @if($status)
        <button class="btn btn-sm btn-primary">
            Active
        </button>
    @else
        <button class="btn btn-sm btn-warning">
            In-Active
        </button>
    @endif
</a>